//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuraFama.RS_BD {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RS_BD.DataBase_WSSoap")]
    public interface DataBase_WSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListarCliente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarClienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CrearCliente(int rut, string nombre, int telefono, int gastos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> CrearClienteAsync(int rut, string nombre, int telefono, int gastos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LeerCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet LeerCliente(int rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LeerCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> LeerClienteAsync(int rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ActualizarCliente(int rut, string nombre, int telefono, int gastos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ActualizarClienteAsync(int rut, string nombre, int telefono, int gastos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet EliminarCliente(int rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> EliminarClienteAsync(int rut);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataBase_WSSoapChannel : PuraFama.RS_BD.DataBase_WSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataBase_WSSoapClient : System.ServiceModel.ClientBase<PuraFama.RS_BD.DataBase_WSSoap>, PuraFama.RS_BD.DataBase_WSSoap {
        
        public DataBase_WSSoapClient() {
        }
        
        public DataBase_WSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataBase_WSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataBase_WSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataBase_WSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet ListarCliente() {
            return base.Channel.ListarCliente();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarClienteAsync() {
            return base.Channel.ListarClienteAsync();
        }
        
        public System.Data.DataSet CrearCliente(int rut, string nombre, int telefono, int gastos) {
            return base.Channel.CrearCliente(rut, nombre, telefono, gastos);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> CrearClienteAsync(int rut, string nombre, int telefono, int gastos) {
            return base.Channel.CrearClienteAsync(rut, nombre, telefono, gastos);
        }
        
        public System.Data.DataSet LeerCliente(int rut) {
            return base.Channel.LeerCliente(rut);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> LeerClienteAsync(int rut) {
            return base.Channel.LeerClienteAsync(rut);
        }
        
        public System.Data.DataSet ActualizarCliente(int rut, string nombre, int telefono, int gastos) {
            return base.Channel.ActualizarCliente(rut, nombre, telefono, gastos);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ActualizarClienteAsync(int rut, string nombre, int telefono, int gastos) {
            return base.Channel.ActualizarClienteAsync(rut, nombre, telefono, gastos);
        }
        
        public System.Data.DataSet EliminarCliente(int rut) {
            return base.Channel.EliminarCliente(rut);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> EliminarClienteAsync(int rut) {
            return base.Channel.EliminarClienteAsync(rut);
        }
    }
}
